version: "2"
volumes:
  mysql_data:
services:
  php_k:
    container_name: "php_k"
    build: ./dockerfiles/php
    volumes:
      - ./../app/:/usr/share/nginx/html
    depends_on:
      - mysql_k
  web_k:
    container_name: "web_k"
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./../app/:/usr/share/nginx/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      -  "php_k"
  mysql_k:
    container_name: "mysql_k"
    image: "mysql:5.7.25"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=app_check24
    ports:
      - "3308:3306"